# Generated by Django 5.1.4 on 2025-01-13 13:49

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='usuarios', variations={'thumb': {'height': 100, 'width': 100}}, verbose_name='Imagem'),
        ),
    ]
