# Generated by Django 3.1 on 2020-11-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hist',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
    ]
