# Generated by Django 5.1.4 on 2025-01-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oee', '0002_auto_20201120_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='horario')),
                ('equipamento', models.IntegerField(verbose_name='Equipamento')),
                ('valor', models.IntegerField(verbose_name='Velocidade')),
            ],
            options={
                'verbose_name': 'Log V',
                'verbose_name_plural': 'Logs V',
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='index')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
            },
        ),
    ]
